#! /bin/sh

## Copyright (C) 2020-2022 Alexandru Balan <alexandru.balan@tutanota.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d 一 二 三 四 五 六
bspc monitor HDMI-A-0 -d 一 二 三 四 五 六

bspc config border_width         	2
bspc config window_gap          	24

bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config pointer_follows_focus 	true
bspc config focus_follows_pointer 	true

# Border
bspc config focused_border_color 	${xrdb:foreground}
bspc config normal_border_color 	${xrdb:background}

#
# Autostart
#
# Set display from arandr saved script
autorandr &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -b &
# Network Applet
nm-applet --indicator &
# Enable numlock on start
numlockx &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
